export const black                  = '#000000';
export const darkGrey               = '#1E1E1E';
export const darkBlue               = '#27354A';
export const grey                   = '#CCCCCC';
export const lightBlue              = '#0C71B1';
export const lightGrey              = '#EFEFEF';
export const white                  = '#FFFFFF';
export const chambray               = '#4E547D'; // topbar
export const purple                 = '#434772'; // bgTop
export const pink                   = '#A8545D'; // bgBottom
export const almond                 = '#8F7D72';
export const antique                = '#BF8369';
export const jellyBean              = '#487A91';
export const zorba                  = '#A1968E';
export const martini                = '#B5AAA3';
export const raven                  = '#686F80';

export const primary                = chambray;
export const secondary              = white;
export const statusBar              = primary;