export const WALLET_ACTIONS = {
    LOAD_WALLET: 'ACTION/WALLET/LOAD_WALLET',
    LOADING: 'ACTION/WALLET/LOADING',
    UPDATE_BALANCE: 'ACTION/WALLET/UPDATE_BALANCE'
};

export const STORAGE_WALLET = '@STORAGE/WALLET';